export const places = [
    'Adlaon',
    'Agsungot',
    'Apas',
    'Babag',
    'Bacayan',
    'Banilad',
    'Basak Pardo',
    'Basak San Nicolas',
    'Binaliw',
    'Bonbon',
    'Budlaan',
    'Buhisan',
    'Bulacao (Bulacao Pardo)',
    'Buot-Taop (Buot‑Taup Pardo)',
    'Busay',
    'Calamba',
    'Cambinocot',
    'Capitol Site',
    'Carreta',
    'Cogon Pardo',
    'Cogon‑Ramos',
    'Day‑as',
    'Duljo Fatima',
    'Ermita',
    'Guadalupe',
    'Guba',
    'Hipodromo',
    'Inayawan (Inayawan Pardo)',
    'Kalubihan',
    'Kalunasan',
    'Kamagayan',
    'Kamputhaw (Camputhaw)',
    'Kasambagan',
    'Kinasang‑an (Kinasang‑an Pardo)',
    'Labangon',
    'Lahug',
    'Lorega‑San Miguel',
    'Lusaran',
    'Luz',
    'Mabini',
    'Mabolo',
    'Malubog',
    'Mambaling',
    'Pahina Central',
    'Pahina San Nicolas',
    'Pamutan',
    'Parian',
    'Paril',
    'Pasil',
    'Pit‑os',
    'Poblacion Pardo',
    'Pulangbato',
    'Pung‑ol Sibugay',
    'Punta Princesa',
    'Quiot (Quiot Pardo)',
    'Sambag I',
    'Sambag II',
    'San Antonio',
    'San Jose',
    'San Nicolas Proper',
    'San Roque',
    'Santa Cruz',
    'Santo Niño',
    'Sapangdaku',
    'Sawang Calero',
    'Sinsin',
    'Sirao',
    'Suba (Suba San Nicolas)',
    'Sudlon I',
    'Sudlon II',
    'T. Padilla',
    'Tabunan',
    'Tag-bao',
    'Talamban',
    'Taptap',
    'Tejero (Villa Gonzalo)',
    'Tinago',
    'Tisa',
    'Toong (To‑ong Pardo)',
    'Zapatera',
]