import DevicesIcon from '@material-ui/icons/Devices';
import FastfoodIcon from '@material-ui/icons/Fastfood';
import LaptopIcon from '@material-ui/icons/Laptop';
import DesktopWindowsIcon from '@material-ui/icons/DesktopWindows';
import PhoneAndroidIcon from '@material-ui/icons/PhoneAndroid';
import TabletAndroidIcon from '@material-ui/icons/TabletAndroid';
import CameraAltIcon from '@material-ui/icons/CameraAlt';
import TvIcon from '@material-ui/icons/Tv';
import SportsEsportsIcon from '@material-ui/icons/SportsEsports';
import HomeIcon from '@material-ui/icons/Home';
import HotelIcon from '@material-ui/icons/Hotel';
import RoomServiceIcon from '@material-ui/icons/RoomService';
import LocalDiningIcon from '@material-ui/icons/LocalDining';
import BathtubIcon from '@material-ui/icons/Bathtub';
import LocalBarIcon from '@material-ui/icons/LocalBar';
import React from 'react';
export const categories = [
    {
        subheaderText: 'Search By Category',
        categoryName: 'Gadgets',
        categoryIcon: <DevicesIcon />,
        link: '',
        subCategory1: 'Laptops',
        subCategoryIcon1: <LaptopIcon />,
        subCategory2: 'Desktops',
        subCategoryIcon2: <DesktopWindowsIcon />,
        subCategory3: 'Mobile Phones',
        subCategoryIcon3: <PhoneAndroidIcon />,
        subCategory4: 'Tablets',
        subCategoryIcon4: <TabletAndroidIcon />,
        subCategory5: 'Cameras',
        subCategoryIcon5: <CameraAltIcon />,
        subCategory6: 'Televisions',
        subCategoryIcon6: <TvIcon />,
        subCategory7: 'Consoles',
        subCategoryIcon7: <SportsEsportsIcon />,
        subCategory8: '',
        subCategoryIcon8: '',
        subCategory9: '',
        subCategoryIcon9: '',
        subCategory10: '',
        subCategoryIcon10:'',
    },
    {
        subheaderText: '',
        categoryName: 'Home & Furnitures',
        categoryIcon: <HomeIcon />,
        link: '',
        subCategory1: 'Living Room',
        subCategoryIcon1: <RoomServiceIcon />,
        subCategory2: 'Bed Room',
        subCategoryIcon2: <HotelIcon />,
        subCategory3: 'Dining Room',
        subCategoryIcon3: <LocalDiningIcon />,
        subCategory4: 'Bath Room',
        subCategoryIcon4: <BathtubIcon />,
        subCategory5: 'Home Appliances',
        subCategoryIcon5: <i className="fas fa-blender-phone"></i>,
        subCategory6: '',
        subCategoryIcon6: '',
        subCategory7: '',
        subCategoryIcon7: '',
        subCategory8: '',
        subCategoryIcon8: '',
        subCategory9: '',
        subCategoryIcon9: '',
        subCategory10: '',
        subCategoryIcon10: '',
    },
    {
        subheaderText: '',
        categoryName: 'Foods & Drinks',
        categoryIcon: <FastfoodIcon />,
        link: '',
        subCategory1: 'Beverages',
        subCategoryIcon1: <i className="fas fa-glass-martini-alt"></i>,
        subCategory2: 'Fruits',
        subCategoryIcon2: <i className="fas fa-apple-alt"></i>,
        subCategory3: 'Homemade Foods',
        subCategoryIcon3: <i className="fas fa-utensils"></i>,
        subCategory4: '',
        subCategoryIcon4: '',
        subCategory5: '',
        subCategoryIcon5: '',
        subCategory6: '',
        subCategoryIcon6: '',
        subCategory7: '',
        subCategoryIcon7: '',
        subCategory8: '',
        subCategoryIcon8: '',
        subCategory9: '',
        subCategoryIcon9: '',
        subCategory10: '',
        subCategoryIcon10: '',
    },
    {
        subheaderText: '',
        categoryName: 'Apparel & Beauty Products',
        categoryIcon: <i className="fas fa-tshirt"></i>,
        link: '',
        subCategory1: 'Men',
        subCategoryIcon1: <i className="fas fa-male"></i>,
        subCategory2: 'Women',
        subCategoryIcon2: <i className="fas fa-female"></i>,
        subCategory3: 'Kids Stuff',
        subCategoryIcon3: <i className="fas fa-child"></i>,
        subCategory4: 'Baby Stuff',
        subCategoryIcon4: <i className="fas fa-baby"></i>,
        subCategory5: '',
        subCategoryIcon5: '',
        subCategory6: '',
        subCategoryIcon6: '',
        subCategory7: '',
        subCategoryIcon7: '',
        subCategory8: '',
        subCategoryIcon8: '',
        subCategory9: '',
        subCategoryIcon9: '',
        subCategory10: '',
        subCategoryIcon10: '',
    },
    {
        subheaderText: '',
        categoryName: 'Properties',
        categoryIcon: <i className="fas fa-building"></i>,
        link: '',
        subCategory1: 'House & Lot',
        subCategoryIcon1: <i className="fas fa-house-user"></i>,
        subCategory2: 'Appartment',
        subCategoryIcon2: <i className="far fa-building"></i>,
        subCategory3: 'Lot Only',
        subCategoryIcon3: <i className="fas fa-splotch"></i>,
        subCategory4: 'Rent to Own Houses',
        subCategoryIcon4: <i className="fas fa-home"></i>,
        subCategory5: 'House for Rent',
        subCategoryIcon5: <i className="fas fa-house-damage"></i>,
        subCategory6: 'Commercial',
        subCategoryIcon6: <i className="fas fa-hotel"></i>,
        subCategory7: '',
        subCategoryIcon7: '',
        subCategory8: '',
        subCategoryIcon8: '',
        subCategory9: '',
        subCategoryIcon9: '',
        subCategory10: '',
        subCategoryIcon10: '',
    },
    {
        subheaderText: '',
        categoryName: 'Outdoor Accessories',
        categoryIcon: <i className="fas fa-universal-access"></i>,
        link: '',
        subCategory1: 'Motorcycle Accessories',
        subCategoryIcon1: <i className="fas fa-motorcycle"></i>,
        subCategory2: 'Sports Accessories',
        subCategoryIcon2: <i className="fas fa-basketball-ball"></i>,
        subCategory3: 'Gym Accessories',
        subCategoryIcon3: <i className="fas fa-dumbbell"></i>,
        subCategory4: 'Wearable Accessories',
        subCategoryIcon4: <i className="fas fa-vest-patches"></i>,
        subCategory5: 'House for Rent',
        subCategoryIcon5: <i className="fas fa-house-damage"></i>,
        subCategory6: 'Bicycle Accessories',
        subCategoryIcon6: <i className="fas fa-bicycle"></i>,
        subCategory7: '',
        subCategoryIcon7: '',
        subCategory8: '',
        subCategoryIcon8: '',
        subCategory9: '',
        subCategoryIcon9: '',
        subCategory10: '',
        subCategoryIcon10: '',
    },
]